### ISSUE TITLE
Home page: Featured image is not utilize for the home page image.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Specialist-Mail-Services#108]
Currently, another field is added for the image.

![image](https://cloud.githubusercontent.com/assets/11186313/6910885/18c66fa8-d78c-11e4-80b1-33fa90133376.png)

**Comment by roseliesromeo** [comment]
Image won't display in front end.

![image](https://cloud.githubusercontent.com/assets/11186313/6911070/3d87837a-d78e-11e4-9a5f-25c7bbacdcf0.png)

**Comment by christiancebudigital** [comment]
please clear your cache...
