### ISSUE TITLE
Header section: Font used for the sub menu is different from the design provided.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Specialist-Mail-Services#15]
Font used per design is Myriad Pro 18px
While in front end is Cutive regular 14px.

![image](https://cloud.githubusercontent.com/assets/11186313/6744547/e6b070c6-cee5-11e4-921a-34d1f2c2ab79.png)

**Comment by christiancebudigital** [comment]
Myriad Pro is blacklisted on font-generator, we used alternative font to match up design..
