### ISSUE TITLE
Homepage: There is white line at the bottom of the banner.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Specialist-Mail-Services#72]
![image](https://cloud.githubusercontent.com/assets/11186313/6749395/bcf0da38-cf2a-11e4-9192-7b4067e5e12e.png)

**Comment by christiancebudigital** [comment]
how to replicate? working on my end..

**Comment by roseliesromeo** [comment]
There is no specific step and I noticed it only happens in a specific monitor screen.  Still able to replicate it though.

![image](https://cloud.githubusercontent.com/assets/11186313/6840317/bc9813e6-d3b0-11e4-9c07-b64be41d91e7.png)
