### ISSUE TITLE
General: Font, logo and buttons are too small.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Specialist-Mail-Services#84]
mobile device.

![image](https://cloud.githubusercontent.com/assets/11186313/6772579/8b0cda80-d13c-11e4-8acb-d2edb12b298c.png)

**Comment by christiancebudigital** [comment]
no psd on mobile, fonts are based on the desktop view.. please explain more on your feedback issue..

**Comment by roseliesromeo** [comment]
Changes are made  

![image](https://cloud.githubusercontent.com/assets/11186313/6840262/cf8c0526-d3af-11e4-8925-28b02d851808.png)
