### ISSUE TITLE
Services single page:  Page layout will be distorted once uploaded with larger featured image.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Specialist-Mail-Services#87]
http://specialist-mail-services.stage.titanweb.com.au/services/service-title-goes-two-lines-long/

![image](https://cloud.githubusercontent.com/assets/11186313/6821826/f51af026-d315-11e4-93f1-a0dd563c0041.png)

**Comment by christiancebudigital** [comment]
need to regenerate thumbnail on order to re-size the image uploaded..
