### ISSUE TITLE
Contact Us page: Address 2 is still displayed even it field is empty at Admin - Business details.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Specialist-Mail-Services#89]
![image](https://cloud.githubusercontent.com/assets/11186313/6822088/f2bcb7d6-d317-11e4-802f-10bec59397e8.png)

**Comment by christiancebudigital** [comment]
I am confused of what do you want me to do, anyway, redundant  display on address in front end is now fixed. condition on address, if address is not empty it will display complete address and it'll show map address, if no address 1 was inputted, it will not display address so as address map...

**Comment by roseliesromeo** [comment]
If address 1 is empty, do not show address in front end (including the map)
If address 1 is not empty, show the complete address (Address 1, Address 2, Suburb, State and Postcode and the address map)

**Comment by christiancebudigital** [comment]
read my comment above, your just rephrased my comment .. >.<

**Comment by roseliesromeo** [comment]
I just made it clearer.  You didn't specify which address field you were referring to with the  'address' in the first condition.
And by the way, I remove fix label because the last time I checked, address 2 won't display.
