### ISSUE TITLE
Home page - Who we are section:  Featured image is elliptical.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Specialist-Mail-Services#94]
IE7 only

![image](https://cloud.githubusercontent.com/assets/11186313/6839960/88be6462-d3ab-11e4-866a-3e5d1d3e73b0.png)

**Comment by christiancebudigital** [comment]
This is fixed on my end... ![whoweare](https://cloud.githubusercontent.com/assets/11186331/6840852/3a146f9a-d3bb-11e4-94ab-d5522a61642f.jpg)

**Comment by roseliesromeo** [comment]
I am still able to replicate the issue

![image](https://cloud.githubusercontent.com/assets/11186313/6863050/acd6eaec-d485-11e4-8f64-a326fcd651cc.png)

**Comment by christiancebudigital** [comment]
wait to fully load the site ie7 browser.. before taking screen shot.. working on my
